### ISSUE TITLE
Promises Support?

### ISSUE THREAD

**Issue by k45514n** [nodebotanist/node-bus-pirate#4]
Thinking about adding support to promises to this library, or should I just leave that up to the user?

Need guidance here.

**Comment by rwaldron** [comment]
IMO any event emitter API supports being a Promise API implicitly, since event can be used to implement any kind of Promise interaction. If you leave it the user, you save yourself from maintaining two interfaces :)

**Comment by timoxley** [comment]
> any event emitter API supports being a Promise API implicitly

@rwaldron …with the condition that the event will only fire once, right? or do you mean something else?

**Comment by HipsterBrown** [comment]
> If you leave it the user, you save yourself from maintaining two interfaces

As @rwaldron told me when working on the `tessel` node module, it's a easier for folks to Promise-ify a callback interface than the other way around, i.e. using [`bluebird.promisify`](http://bluebirdjs.com/docs/api/promise.promisify.html). Adding an example of this usage in the docs can be helpful and quicker solution than the two interfaces.

**Comment by noopkat** [comment]
Promises are loved by some, loathed by others, and the remaining are 'meh'. Love the idea of providing the option of promisifying for those really into it, via Bluebird etc. I take this approach with my own OSS so I'm a bit biased this way to begin with.

**Comment by rwaldron** [comment]
@timoxley any and every event handler can be written as "handle once" operation. The events themselves aren't obligated to any such limitation.

**Comment by k45514n** [comment]
Okay after a welcome outpouring of advice, I'm going to NOT implement promises. Thanks all!
